<?php

namespace ContainerZxxMVYs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EWzQKNpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eWzQKNp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eWzQKNp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'registrationTokenRepository' => ['privates', 'App\\Repository\\RegistrationTokenRepository', 'getRegistrationTokenRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'registrationTokenRepository' => 'App\\Repository\\RegistrationTokenRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
