<?php

namespace Container2JZzXbx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gk1XrxxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gk1Xrxx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gk1Xrxx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaryRepository' => ['privates', 'App\\Repository\\CommentaryRepository', 'getCommentaryRepositoryService', true],
            'trickRepository' => ['privates', 'App\\Repository\\TrickRepository', 'getTrickRepositoryService', true],
        ], [
            'commentaryRepository' => 'App\\Repository\\CommentaryRepository',
            'trickRepository' => 'App\\Repository\\TrickRepository',
        ]);
    }
}
