twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        images_directory: '/uploads/tricks/'
        avatars_directory: '/uploads/avatars/'
when@test:
    twig:
        strict_variables: true
