<?php

namespace Container5RWw691;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Z0tXHJlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.z0tXHJl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.z0tXHJl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'tokenRepository' => ['privates', 'App\\Repository\\TokenRepository', 'getTokenRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'passwordHasher' => '?',
            'tokenRepository' => 'App\\Repository\\TokenRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
