<?php

namespace ContainerWti5ufv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R1fpUxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r1fp_Ux' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r1fp_Ux'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'registrationTokenRepository' => ['privates', 'App\\Repository\\TokenRepository', 'getTokenRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'registrationTokenRepository' => 'App\\Repository\\TokenRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
