<?php

namespace ContainerPbodRzV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_13WLsVFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.13WLsVF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.13WLsVF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'tokenRepository' => ['privates', 'App\\Repository\\RegistrationTokenRepository', 'getRegistrationTokenRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'doctrine' => '?',
            'passwordHasher' => '?',
            'tokenRepository' => 'App\\Repository\\RegistrationTokenRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
