<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Trick extends \App\Entity\Trick implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'publishedDate', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'lastUpdated', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'group', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'User', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'medias', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'mainMedia', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'commentaries'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'publishedDate', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'lastUpdated', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'group', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'User', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'medias', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'mainMedia', '' . "\0" . 'App\\Entity\\Trick' . "\0" . 'commentaries'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Trick $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Trick
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Trick
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublishedDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublishedDate', []);

        return parent::getPublishedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublishedDate(\DateTimeInterface $publishedDate): \App\Entity\Trick
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublishedDate', [$publishedDate]);

        return parent::setPublishedDate($publishedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUpdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUpdated', []);

        return parent::getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastUpdated(?\DateTimeInterface $lastUpdated): \App\Entity\Trick
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastUpdated', [$lastUpdated]);

        return parent::setLastUpdated($lastUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroup(): ?\App\Entity\Group
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroup', []);

        return parent::getGroup();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroup(?\App\Entity\Group $group): \App\Entity\Trick
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroup', [$group]);

        return parent::setGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $User): \App\Entity\Trick
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$User]);

        return parent::setUser($User);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedias(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedias', []);

        return parent::getMedias();
    }

    /**
     * {@inheritDoc}
     */
    public function addMedia(\App\Entity\Media $media): \App\Entity\Trick
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMedia', [$media]);

        return parent::addMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMedia(\App\Entity\Media $media): \App\Entity\Trick
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMedia', [$media]);

        return parent::removeMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainMedia(): ?\App\Entity\Media
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainMedia', []);

        return parent::getMainMedia();
    }

    /**
     * {@inheritDoc}
     */
    public function setMainMedia(?\App\Entity\Media $mainMedia): \App\Entity\Trick
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMainMedia', [$mainMedia]);

        return parent::setMainMedia($mainMedia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaries(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaries', []);

        return parent::getCommentaries();
    }

    /**
     * {@inheritDoc}
     */
    public function purgeTrick(\App\Repository\CommentaryRepository $commentaryRepository, \App\Repository\MediaRepository $mediaRepository): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'purgeTrick', [$commentaryRepository, $mediaRepository]);

        return parent::purgeTrick($commentaryRepository, $mediaRepository);
    }

    /**
     * {@inheritDoc}
     */
    public function addCommentary(\App\Entity\Commentary $commentary): \App\Entity\Trick
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommentary', [$commentary]);

        return parent::addCommentary($commentary);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommentary(\App\Entity\Commentary $commentary): \App\Entity\Trick
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommentary', [$commentary]);

        return parent::removeCommentary($commentary);
    }

}
