<?php

namespace ContainerHvblZzf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PaAAmnaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.paAAmna' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.paAAmna'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaryRepository' => ['privates', 'App\\Repository\\CommentaryRepository', 'getCommentaryRepositoryService', true],
            'mediaRepository' => ['privates', 'App\\Repository\\MediaRepository', 'getMediaRepositoryService', true],
            'trick' => ['privates', '.errored..service_locator.paAAmna.App\\Entity\\Trick', NULL, 'Cannot autowire service ".service_locator.paAAmna": it references class "App\\Entity\\Trick" but no such service exists.'],
            'trickRepository' => ['privates', 'App\\Repository\\TrickRepository', 'getTrickRepositoryService', true],
        ], [
            'commentaryRepository' => 'App\\Repository\\CommentaryRepository',
            'mediaRepository' => 'App\\Repository\\MediaRepository',
            'trick' => 'App\\Entity\\Trick',
            'trickRepository' => 'App\\Repository\\TrickRepository',
        ]);
    }
}
