<?php

namespace ContainerHvblZzf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMediaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cME2Xsc.App\Entity\Media' shared service.
     *
     * @return \App\Entity\Media
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cME2Xsc": it references class "App\\Entity\\Media" but no such service exists.');
    }
}
