<?php

namespace ContainerAuYwRk0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W2G6oTaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W2G6oTa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W2G6oTa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaryRepository' => ['privates', 'App\\Repository\\CommentaryRepository', 'getCommentaryRepositoryService', true],
            'trick' => ['privates', '.errored..service_locator.W2G6oTa.App\\Entity\\Trick', NULL, 'Cannot autowire service ".service_locator.W2G6oTa": it references class "App\\Entity\\Trick" but no such service exists.'],
        ], [
            'commentaryRepository' => 'App\\Repository\\CommentaryRepository',
            'trick' => 'App\\Entity\\Trick',
        ]);
    }
}
