<?php

namespace ContainerAuYwRk0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PSe2ZZ2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PSe2ZZ2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PSe2ZZ2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mediaRepository' => ['privates', 'App\\Repository\\MediaRepository', 'getMediaRepositoryService', true],
            'trickRepository' => ['privates', 'App\\Repository\\TrickRepository', 'getTrickRepositoryService', true],
        ], [
            'mediaRepository' => 'App\\Repository\\MediaRepository',
            'trickRepository' => 'App\\Repository\\TrickRepository',
        ]);
    }
}
