<?php

namespace ContainerAuYwRk0;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E9zJ0mxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e9zJ0mx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e9zJ0mx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'trick' => ['privates', '.errored..service_locator.e9zJ0mx.App\\Entity\\Trick', NULL, 'Cannot autowire service ".service_locator.e9zJ0mx": it references class "App\\Entity\\Trick" but no such service exists.'],
            'trickRepository' => ['privates', 'App\\Repository\\TrickRepository', 'getTrickRepositoryService', true],
        ], [
            'trick' => 'App\\Entity\\Trick',
            'trickRepository' => 'App\\Repository\\TrickRepository',
        ]);
    }
}
