<?php

namespace ContainerGXoseEi;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DpNz4YAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DpNz4YA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DpNz4YA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'registrationTokenRepository' => ['privates', 'App\\Repository\\RegistrationTokenRepository', 'getRegistrationTokenRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'registrationTokenRepository' => 'App\\Repository\\RegistrationTokenRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
