<?php

namespace ContainerEfViYUs;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gp7YyaJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gp7YyaJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gp7YyaJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'session' => ['privates', '.errored..service_locator.Gp7YyaJ.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator.Gp7YyaJ": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists.'],
            'trickRepository' => ['privates', 'App\\Repository\\TrickRepository', 'getTrickRepositoryService', true],
        ], [
            'session' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
            'trickRepository' => 'App\\Repository\\TrickRepository',
        ]);
    }
}
