<?php

namespace Container8yLrVHy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YEDSq3sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YEDSq3s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YEDSq3s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commentaryRepository' => ['privates', 'App\\Repository\\CommentaryRepository', 'getCommentaryRepositoryService', true],
            'session' => ['privates', '.errored..service_locator.YEDSq3s.Symfony\\Component\\HttpFoundation\\Session\\Session', NULL, 'Cannot autowire service ".service_locator.YEDSq3s": it references class "Symfony\\Component\\HttpFoundation\\Session\\Session" but no such service exists.'],
            'trickRepository' => ['privates', 'App\\Repository\\TrickRepository', 'getTrickRepositoryService', true],
        ], [
            'commentaryRepository' => 'App\\Repository\\CommentaryRepository',
            'session' => 'Symfony\\Component\\HttpFoundation\\Session\\Session',
            'trickRepository' => 'App\\Repository\\TrickRepository',
        ]);
    }
}
