<?php

namespace ContainerNwxISxQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UKwsrplService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UKwsrpl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UKwsrpl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'registrationTokenRepository' => ['privates', 'App\\Repository\\RegistrationTokenRepository', 'getRegistrationTokenRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.UKwsrpl.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.UKwsrpl": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'registrationTokenRepository' => 'App\\Repository\\RegistrationTokenRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
