<?php

namespace ContainerH8C6xZq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1UljFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.__1UljF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.__1UljF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'registrationTokenRepository' => ['privates', 'App\\Repository\\RegistrationTokenRepository', 'getRegistrationTokenRepositoryService', true],
            'token' => ['privates', '.errored..service_locator.__1UljF.Symfony\\Component\\Uid\\Uuid', NULL, 'Cannot autowire service ".service_locator.__1UljF": it references class "Symfony\\Component\\Uid\\Uuid" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.__1UljF.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.__1UljF": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'registrationTokenRepository' => 'App\\Repository\\RegistrationTokenRepository',
            'token' => 'Symfony\\Component\\Uid\\Uuid',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
