<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXafOUWK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXafOUWK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXafOUWK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXafOUWK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXafOUWK\App_KernelDevDebugContainer([
    'container.build_hash' => 'XafOUWK',
    'container.build_id' => '1dd62e0b',
    'container.build_time' => 1664113911,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXafOUWK');
