<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG3lAN1E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG3lAN1E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG3lAN1E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG3lAN1E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG3lAN1E\App_KernelDevDebugContainer([
    'container.build_hash' => 'G3lAN1E',
    'container.build_id' => 'fa73b5cc',
    'container.build_time' => 1664115219,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG3lAN1E');
